export const cardList = [
    {
        id: 1,
        title: "Задача 1",
        topic: "Web Design",
        date: "10.05.2024",
        status: "Без статуса",
    },
    {
        id: 1,
        title: "Задача 2",
        topic: "Web Design",
        date: "10.05.2024",
        status: "Без статуса",
    },
    {
        id: 1,
        title: "Задача 3",
        topic: "Web Design",
        date: "10.05.2024",
        status: "Без статуса",
    },
    {
        id: 1,
        title: "Задача 4",
        topic: "Web Design",
        date: "10.05.2024",
        status: "Без статуса",
    },
    {
        id: 2,
        title: "Задача 5",
        topic: "Copywriting",
        date: "10.05.2024",
        status: "Нужно сделать",
    },
    {
        id: 3,
        title: "Задача 6",
        topic: "Research",
        date: "10.05.2024",
        status: "В работе",
    },
    {
        id: 3,
        title: "Задача 7",
        topic: "Research",
        date: "10.05.2024",
        status: "В работе",
    },
    {
        id: 4,
        title: "Задача 8",
        topic: "Research",
        date: "10.05.2024",
        status: "Тестирование",
    },
    {
        id: 5,
        title: "Задача 9",
        topic: "Research",
        date: "10.05.2024",
        status: "Готово",
    },
    {
        id: 5,
        title: "Задача 10",
        topic: "Research",
        date: "10.05.2024",
        status: "Готово",
    },
    {
        id: 5,
        title: "Задача 11",
        topic: "Research",
        date: "10.05.2024",
        status: "Готово",
    },
];